spring:
<<<<<<< HEAD
  profiles:
    active: local
=======
>>>>>>> e5ec865c52526804de6b0681862a4c751c14de32
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: create-drop
>>>>>>> e5ec865c52526804de6b0681862a4c751c14de32
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
